services:
  aziral-video-gen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aziral-video-gen
    restart: always
    volumes:
      - ./config.toml:/MoneyPrinterTurbo/config.toml
      - ./storage:/MoneyPrinterTurbo/storage
    networks:
      - fenix-global-network

networks:
  fenix-global-network:
    external: true
